#!/bin/sh
#
# @name Quad Tilting Custom - OmniQuad Style
#
# @type Tilting Multirotor
# @class Copter
#
# @output MAIN1 Motor 1 front-right (XING2 2809 1250KV)
# @output MAIN2 Motor 2 rear-left   (XING2 2809 1250KV)
# @output MAIN3 Motor 3 front-left  (XING2 2809 1250KV)
# @output MAIN4 Motor 4 rear-right  (XING2 2809 1250KV)
# @output MAIN5 Servo 1 front-right (SPT4412LV)
# @output MAIN6 Servo 2 rear-left   (SPT4412LV)
# @output MAIN7 Servo 3 front-left  (SPT4412LV)
# @output MAIN8 Servo 4 rear-right  (SPT4412LV)
#
# @board px4_fmu-v2 exclude
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.mc_defaults

param set-default MAV_TYPE 2

# 4 rotors
param set-default CA_ROTOR_COUNT 4

# Motor 1 - front right
param set-default CA_ROTOR0_PX  0.166
param set-default CA_ROTOR0_PY  0.166
param set-default CA_ROTOR0_PZ  0.0
param set-default CA_ROTOR0_KM  0.05

# Motor 2 - rear left
param set-default CA_ROTOR1_PX -0.166
param set-default CA_ROTOR1_PY -0.166
param set-default CA_ROTOR1_PZ  0.0
param set-default CA_ROTOR1_KM  0.05

# Motor 3 - front left
param set-default CA_ROTOR2_PX  0.166
param set-default CA_ROTOR2_PY -0.166
param set-default CA_ROTOR2_PZ  0.0
param set-default CA_ROTOR2_KM -0.05

# Motor 4 - rear right
param set-default CA_ROTOR3_PX -0.166
param set-default CA_ROTOR3_PY  0.166
param set-default CA_ROTOR3_PZ  0.0
param set-default CA_ROTOR3_KM -0.05

# 4 tilt servos
param set-default CA_SV_TL_COUNT 4

param set-default CA_SV_TL0_MINA -30.0
param set-default CA_SV_TL0_MAXA  30.0
param set-default CA_SV_TL0_TD    90

param set-default CA_SV_TL1_MINA -30.0
param set-default CA_SV_TL1_MAXA  30.0
param set-default CA_SV_TL1_TD    90

param set-default CA_SV_TL2_MINA -30.0
param set-default CA_SV_TL2_MAXA  30.0
param set-default CA_SV_TL2_TD    90

param set-default CA_SV_TL3_MINA -30.0
param set-default CA_SV_TL3_MAXA  30.0
param set-default CA_SV_TL3_TD    90

# Direct output assignment - OmniQuad approach (PWM_MAIN_FUNC)
# Motors → MAIN 1-4
param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104

# Tilt Servos → MAIN 5-8
param set-default PWM_MAIN_FUNC5 201
param set-default PWM_MAIN_FUNC6 202
param set-default PWM_MAIN_FUNC7 203
param set-default PWM_MAIN_FUNC8 204

# MAIN rate 50Hz for servos SPT4412LV
param set-default PWM_MAIN_RATE 50
param set-default PWM_MAIN_MIN  1000
param set-default PWM_MAIN_MAX  2000

# Force IO coprocessor for MAIN outputs
param set-default SYS_USE_IO 1
