#!/bin/sh
#
# @name gaya
#
# @type Quadrotor x
# @class Copter
#
# @output AUX1 Motor 1 front-right (XING2 2809 1250KV)
# @output AUX2 Motor 2 rear-left   (XING2 2809 1250KV)
# @output AUX3 Motor 3 front-left  (XING2 2809 1250KV)
# @output AUX4 Motor 4 rear-right  (XING2 2809 1250KV)
# @output MAIN1 Servo 1 tilt front-right (SPT4412LV)
# @output MAIN2 Servo 2 tilt rear-left   (SPT4412LV)
# @output MAIN3 Servo 3 tilt front-left  (SPT4412LV)
# @output MAIN4 Servo 4 tilt rear-right  (SPT4412LV)
#
# @board px4_fmu-v2 exclude
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.mc_defaults

param set-default MAV_TYPE 2

# ---- OmniQuad allocator activation (CRITICAL) ----
# CA_AIRFRAME = 13 -> EffectivenessSource::TILTING_MULTIROTOR
# CA_TILTING_TYPE = 1 -> Fully actuated (omnidirectional)
param set-default CA_AIRFRAME 13
param set-default CA_TILTING_TYPE 1

# ---- 4 rotors geometry (X quad, arms ~0.166 m) ----
param set-default CA_ROTOR_COUNT 4

# Motor 1 - front right - CCW
param set-default CA_ROTOR0_PX  0.166
param set-default CA_ROTOR0_PY  0.166
param set-default CA_ROTOR0_PZ  0.0
param set-default CA_ROTOR0_KM  0.05

# Motor 2 - rear left - CCW
param set-default CA_ROTOR1_PX -0.166
param set-default CA_ROTOR1_PY -0.166
param set-default CA_ROTOR1_PZ  0.0
param set-default CA_ROTOR1_KM  0.05

# Motor 3 - front left - CW
param set-default CA_ROTOR2_PX  0.166
param set-default CA_ROTOR2_PY -0.166
param set-default CA_ROTOR2_PZ  0.0
param set-default CA_ROTOR2_KM -0.05

# Motor 4 - rear right - CW
param set-default CA_ROTOR3_PX -0.166
param set-default CA_ROTOR3_PY  0.166
param set-default CA_ROTOR3_PZ  0.0
param set-default CA_ROTOR3_KM -0.05

# ---- 4 tilt servos ----
param set-default CA_SV_TL_COUNT 4

param set-default CA_SV_TL0_MINA -30.0
param set-default CA_SV_TL0_MAXA  30.0
param set-default CA_SV_TL0_TD    90

param set-default CA_SV_TL1_MINA -30.0
param set-default CA_SV_TL1_MAXA  30.0
param set-default CA_SV_TL1_TD    90

param set-default CA_SV_TL2_MINA -30.0
param set-default CA_SV_TL2_MAXA  30.0
param set-default CA_SV_TL2_TD    90

param set-default CA_SV_TL3_MINA -30.0
param set-default CA_SV_TL3_MAXA  30.0
param set-default CA_SV_TL3_TD    90

# ---- Output assignment (Pixhawk 6C) ----
# Motors -> PWM AUX (FMU direct, fast PWM/DShot)
# Tilts  -> PWM MAIN (IO coprocessor, 50 Hz, safe for analog servos)
#
# Function codes: 101..104 = Motor 1..4 ; 201..204 = Servo 1..4

# Motors on AUX 1-4
param set-default PWM_AUX_FUNC1 101
param set-default PWM_AUX_FUNC2 102
param set-default PWM_AUX_FUNC3 103
param set-default PWM_AUX_FUNC4 104

# Tilt servos on MAIN 1-4
param set-default PWM_MAIN_FUNC1 201
param set-default PWM_MAIN_FUNC2 202
param set-default PWM_MAIN_FUNC3 203
param set-default PWM_MAIN_FUNC4 204

# ---- Per-channel PWM settings (PX4 1.14+ uses per-channel params) ----

# AUX (motors): rate 400 Hz on each timer group (Pixhawk 6C has 3 timer groups on AUX)
param set-default PWM_AUX_TIM0 400
param set-default PWM_AUX_TIM1 400
param set-default PWM_AUX_TIM2 400

# AUX channels 1..4 (motors): disarm = 900 us (off), min = 1000, max = 2000
param set-default PWM_AUX_DIS1 900
param set-default PWM_AUX_DIS2 900
param set-default PWM_AUX_DIS3 900
param set-default PWM_AUX_DIS4 900
param set-default PWM_AUX_MIN1 1000
param set-default PWM_AUX_MIN2 1000
param set-default PWM_AUX_MIN3 1000
param set-default PWM_AUX_MIN4 1000
param set-default PWM_AUX_MAX1 2000
param set-default PWM_AUX_MAX2 2000
param set-default PWM_AUX_MAX3 2000
param set-default PWM_AUX_MAX4 2000

# AUX failsafe = same as disarm (motors stop on RC loss)
param set-default PWM_AUX_FAIL1 900
param set-default PWM_AUX_FAIL2 900
param set-default PWM_AUX_FAIL3 900
param set-default PWM_AUX_FAIL4 900

# MAIN (servos): rate 50 Hz on each timer group
param set-default PWM_MAIN_TIM0 50
param set-default PWM_MAIN_TIM1 50
param set-default PWM_MAIN_TIM2 50

# MAIN channels 1..4 (tilt servos): disarm = 1500 us (neutral 0 deg), min/max for full course
param set-default PWM_MAIN_DIS1 1500
param set-default PWM_MAIN_DIS2 1500
param set-default PWM_MAIN_DIS3 1500
param set-default PWM_MAIN_DIS4 1500
param set-default PWM_MAIN_MIN1 1000
param set-default PWM_MAIN_MIN2 1000
param set-default PWM_MAIN_MIN3 1000
param set-default PWM_MAIN_MIN4 1000
param set-default PWM_MAIN_MAX1 2000
param set-default PWM_MAIN_MAX2 2000
param set-default PWM_MAIN_MAX3 2000
param set-default PWM_MAIN_MAX4 2000

# MAIN failsafe = neutral (servos return to 0 deg on RC loss)
param set-default PWM_MAIN_FAIL1 1500
param set-default PWM_MAIN_FAIL2 1500
param set-default PWM_MAIN_FAIL3 1500
param set-default PWM_MAIN_FAIL4 1500

# Use IO coprocessor for MAIN (safer for servos)
param set-default SYS_USE_IO 1
