#!/bin/sh
#
# @name gaya
#
# @type Quadrotor x
# @class Copter
#
# @output AUX1 Motor 1 front-right (XING2 2809 1250KV)
# @output AUX2 Motor 2 rear-left   (XING2 2809 1250KV)
# @output AUX3 Motor 3 front-left  (XING2 2809 1250KV)
# @output AUX4 Motor 4 rear-right  (XING2 2809 1250KV)
# @output AUX5 Servo 1 tilt front-right (SPT4412LV)
# @output AUX6 Servo 2 tilt rear-left   (SPT4412LV)
# @output AUX7 Servo 3 tilt front-left  (SPT4412LV)
# @output AUX8 Servo 4 tilt rear-right  (SPT4412LV)
#
# Pixhawk 6C has NO PX4IO coprocessor: all 8 outputs are FMU/AUX.
# Timer groups (from boards/px4/fmu-v6c/src/timer_config.cpp):
#   TIM0 (TIM1): AUX 1-4   -> motors at 400 Hz
#   TIM1 (TIM4): AUX 5-6   -> servos at 50 Hz
#   TIM2 (TIM5): AUX 7-8   -> servos at 50 Hz
#
# @board px4_fmu-v2 exclude
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.mc_defaults

param set-default MAV_TYPE 2

# ---- OmniQuad allocator activation (CRITICAL) ----
# CA_AIRFRAME = 13 -> EffectivenessSource::TILTING_MULTIROTOR
# CA_TILTING_TYPE = 1 -> Fully actuated (omnidirectional)
param set-default CA_AIRFRAME 13
param set-default CA_TILTING_TYPE 1

# ---- 4 rotors geometry (X quad, arms ~0.166 m) ----
param set-default CA_ROTOR_COUNT 4

# Motor 1 - front right - CCW - tilted by Tilt 1
param set-default CA_ROTOR0_PX  0.166
param set-default CA_ROTOR0_PY  0.166
param set-default CA_ROTOR0_PZ  0.0
param set-default CA_ROTOR0_KM  0.05
param set-default CA_ROTOR0_TILT 1

# Motor 2 - rear left - CCW - tilted by Tilt 2
param set-default CA_ROTOR1_PX -0.166
param set-default CA_ROTOR1_PY -0.166
param set-default CA_ROTOR1_PZ  0.0
param set-default CA_ROTOR1_KM  0.05
param set-default CA_ROTOR1_TILT 2

# Motor 3 - front left - CW - tilted by Tilt 3
param set-default CA_ROTOR2_PX  0.166
param set-default CA_ROTOR2_PY -0.166
param set-default CA_ROTOR2_PZ  0.0
param set-default CA_ROTOR2_KM -0.05
param set-default CA_ROTOR2_TILT 3

# Motor 4 - rear right - CW - tilted by Tilt 4
param set-default CA_ROTOR3_PX -0.166
param set-default CA_ROTOR3_PY  0.166
param set-default CA_ROTOR3_PZ  0.0
param set-default CA_ROTOR3_KM -0.05
param set-default CA_ROTOR3_TILT 4

# ---- 4 tilt servos ----
param set-default CA_SV_TL_COUNT 4

param set-default CA_SV_TL0_MINA -30.0
param set-default CA_SV_TL0_MAXA  30.0
param set-default CA_SV_TL0_TD    90

param set-default CA_SV_TL1_MINA -30.0
param set-default CA_SV_TL1_MAXA  30.0
param set-default CA_SV_TL1_TD    90

param set-default CA_SV_TL2_MINA -30.0
param set-default CA_SV_TL2_MAXA  30.0
param set-default CA_SV_TL2_TD    90

param set-default CA_SV_TL3_MINA -30.0
param set-default CA_SV_TL3_MAXA  30.0
param set-default CA_SV_TL3_TD    90

# ---- Output assignment (Pixhawk 6C: all 8 channels are FMU/AUX) ----
# Function codes: 101..104 = Motor 1..4 ; 201..204 = Servo 1..4
#
# Motors on AUX 1-4 (FMU PWM 1-4, TIM1, fast PWM/DShot)
param set-default PWM_AUX_FUNC1 101
param set-default PWM_AUX_FUNC2 102
param set-default PWM_AUX_FUNC3 103
param set-default PWM_AUX_FUNC4 104

# Tilt servos on AUX 5-8 (FMU PWM 5-8, TIM4+TIM5, 50 Hz analog PWM)
param set-default PWM_AUX_FUNC5 201
param set-default PWM_AUX_FUNC6 202
param set-default PWM_AUX_FUNC7 203
param set-default PWM_AUX_FUNC8 204

# Disable MAIN explicitly: 6C has no PX4IO chip, MAIN rail is non-functional
param set-default PWM_MAIN_FUNC1 0
param set-default PWM_MAIN_FUNC2 0
param set-default PWM_MAIN_FUNC3 0
param set-default PWM_MAIN_FUNC4 0
param set-default PWM_MAIN_FUNC5 0
param set-default PWM_MAIN_FUNC6 0
param set-default PWM_MAIN_FUNC7 0
param set-default PWM_MAIN_FUNC8 0

# ---- Per-channel PWM AUX settings ----

# Timer rates: motors fast (400 Hz), servos slow (50 Hz)
# TIM0 covers AUX 1-4 (motors), TIM1 covers AUX 5-6, TIM2 covers AUX 7-8 (servos)
param set-default PWM_AUX_TIM0 400
param set-default PWM_AUX_TIM1  50
param set-default PWM_AUX_TIM2  50

# Disarm: motors off (900 us), servos at neutral (1500 us = 0 deg)
param set-default PWM_AUX_DIS1 900
param set-default PWM_AUX_DIS2 900
param set-default PWM_AUX_DIS3 900
param set-default PWM_AUX_DIS4 900
param set-default PWM_AUX_DIS5 1500
param set-default PWM_AUX_DIS6 1500
param set-default PWM_AUX_DIS7 1500
param set-default PWM_AUX_DIS8 1500

# Min PWM (1000 us = 0% throttle / -30 deg servo)
param set-default PWM_AUX_MIN1 1000
param set-default PWM_AUX_MIN2 1000
param set-default PWM_AUX_MIN3 1000
param set-default PWM_AUX_MIN4 1000
param set-default PWM_AUX_MIN5 1000
param set-default PWM_AUX_MIN6 1000
param set-default PWM_AUX_MIN7 1000
param set-default PWM_AUX_MIN8 1000

# Max PWM (2000 us = 100% throttle / +30 deg servo)
param set-default PWM_AUX_MAX1 2000
param set-default PWM_AUX_MAX2 2000
param set-default PWM_AUX_MAX3 2000
param set-default PWM_AUX_MAX4 2000
param set-default PWM_AUX_MAX5 2000
param set-default PWM_AUX_MAX6 2000
param set-default PWM_AUX_MAX7 2000
param set-default PWM_AUX_MAX8 2000

# Failsafe: motors stop, servos return to neutral on RC loss
param set-default PWM_AUX_FAIL1 900
param set-default PWM_AUX_FAIL2 900
param set-default PWM_AUX_FAIL3 900
param set-default PWM_AUX_FAIL4 900
param set-default PWM_AUX_FAIL5 1500
param set-default PWM_AUX_FAIL6 1500
param set-default PWM_AUX_FAIL7 1500
param set-default PWM_AUX_FAIL8 1500
